### ISSUE TITLE
您好，请问项目是还没有开发完毕吗？

### ISSUE THREAD

**Issue by greysonOuyang** [wenMN1994/fuwah#1]
我把系统运行起来了，但是好像几个模块暂时没有实现是吗？

**Comment by wenMN1994** [comment]
还没开发完哦。

Thanks & Best regards,
温文星 · Dragon Wen
___________________________________________________________________________
广东省深圳市
http://dragonwen.top
Dragon Wen · 温文星
Phone: 18129954693
mailto:18475536452@163.com


发件人: Greyson
发送时间: 2020年3月28日 20:55
收件人: wenMN1994/fuwah
抄送: Subscribed
主题: [wenMN1994/fuwah] 您好，请问项目是还没有开发完毕吗？ (#1)

我把系统运行起来了，但是好像几个模块暂时没有实现是吗？
